# Generated by Django 2.0.7 on 2018-07-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='picture',
            field=models.ImageField(upload_to='img'),
        ),
    ]
