# Generated by Django 2.0.7 on 2018-07-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180729_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='username',
        ),
        migrations.AddField(
            model_name='choice',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
