# Generated by Django 2.0.7 on 2018-07-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180729_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='user_time',
            new_name='use_time',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='left_pic_title',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='right_pic_title',
        ),
        migrations.AlterField(
            model_name='choice',
            name='left_pic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='right_pic',
            field=models.IntegerField(),
        ),
    ]
