# Generated by Django 2.0.7 on 2018-07-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180729_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='left_pic',
            new_name='left_pic_id',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='right_pic',
            new_name='right_pic_id',
        ),
    ]
