# Generated by Django 2.0.7 on 2018-07-31 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180729_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='group_name',
        ),
        migrations.AddField(
            model_name='pool',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choose_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 14, 53, 14, 519601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
