# Generated by Django 2.0.7 on 2018-07-31 16:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180731_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choose_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 16, 3, 1, 720847, tzinfo=utc)),
        ),
    ]
