# Generated by Django 2.0.7 on 2018-07-31 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180801_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choose_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 16, 6, 33, 77621, tzinfo=utc)),
        ),
    ]
