# Generated by Django 2.0.7 on 2018-07-31 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180801_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choose_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 16, 7, 29, 991702, tzinfo=utc)),
        ),
    ]
