# Generated by Django 2.0.7 on 2018-07-31 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180801_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='picture',
            new_name='pic',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choose_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 16, 9, 4, 235159, tzinfo=utc)),
        ),
    ]
