# Generated by Django 2.0.7 on 2018-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180801_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choose_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
