# Generated by Django 2.0.7 on 2018-08-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180801_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='operator',
            field=models.IntegerField(choices=[(0, '标注用户'), (1, '测试用户'), (2, '管理员用户'), (3, '超级管理员')], default=0, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
