# Generated by Django 2.0.7 on 2018-08-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180803_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '标注信息', 'verbose_name_plural': '标注信息'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '标签管理', 'verbose_name_plural': '标签管理'},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'verbose_name': '图片管理', 'verbose_name_plural': '图片管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户组'},
        ),
        migrations.RemoveField(
            model_name='pool',
            name='group_id',
        ),
        migrations.AddField(
            model_name='pool',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Group'),
            preserve_default=False,
        ),
    ]
