# Generated by Django 2.0.7 on 2018-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20180804_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=255, verbose_name='data_name')),
                ('data_value', models.CharField(max_length=255, verbose_name='data_value')),
                ('enable_flag', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
        ),
    ]
