# Generated by Django 2.0.7 on 2018-08-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='enable_flag',
            field=models.BooleanField(default=True),
        ),
    ]
